# In _config.yml
title: Imagining Futures repository documentation
author: Imagining Futures repository team
logo: _static/imgs/logo-if.png
only_build_toc_files: true

execute:
  execute_notebooks: force
  allow_errors: true
  timeout: 200
  exclude_patterns:
    - "tmp*"
    - "test*"
    - "private*" # exclude private notebooks

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/ImaginingFutures/if-documentation # Online location of your book
  #path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: gh-pages # Which branch of the repository should be used when creating links (optional)

html:
  use_issues_button: true
  use_repository_button: true
  # google_analytics_id: G-QKKV7Q3XE3
  extra_navbar: Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
  extra_footer: v. Î± [09-08-2023]<br /><a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.

sphinx:
  config:
    html_show_copyright: false
    bibtex_reference_style: author_year
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
